version: '3'
services:
  app:
    build:
      context: .
      dockerfile: currbot.dockerfile
    image: lnugo/currbot:latest
    container_name: currbot_app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
  mongo:
    image: mongo:4.4.18
    container_name: currbot_mongo
    command: mongod --port ${MONGO_PORT}
    volumes:
      - mongo-currbot:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongo-currbot: